// The evaluation table of the tile set, from the app's own code (the shared walking rules, the usable-space check and the twelve matrix descriptors), written to
// engine/tiles/v7/EVALUATION.md so docs/TILE_SET_V7.md can quote it.   npx tsx scripts/tiles/table.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { usableSpace } from "../../lib/scoring/usable";
import { evaluateTile } from "../../lib/scoring/matrixEval";
import { getOcc, getWalk } from "../../lib/arrange/occupancy";
import { getOriented } from "../../lib/arrange/orient";
import { printChecks } from "../../lib/tiles/checks";
import { loadFixture, TILE_ORDER } from "./load";

const rows1: string[] = [];
const rows2: string[] = [];
const keys: string[] = [];
const fmt = (v: number | null) => (v === null ? "n/a" : Math.abs(v) >= 100 ? v.toFixed(0) : v.toFixed(Math.abs(v) < 10 ? 2 : 1));
const units: string[] = [];
const rows3: string[] = [];
const checkKeys: string[] = [];
const checkRows: { tag: string; by: Record<string, string> }[] = [];
for (const n of TILE_ORDER) {
  const t = loadFixture(n)!;
  const u = usableSpace(t);
  const e = evaluateTile(t);
  const wk = getWalk(getOcc(getOriented(t, 0, false)));
  const zs = wk.zones.filter((z) => z.significant);
  const main = zs.find((z) => z.id === wk.main)?.areaFt2 ?? 0;
  const tag = n.replace(/^(gathering|office|lobby)_(\d)_.*/, (_, c: string, i: string) => `${c[0].toUpperCase()}${i}`);
  rows1.push(`| ${tag} | ${t.tileFt.join(" x ")} | ${(100 * u.usableFt2 / Math.max(1, u.floorFt2)).toFixed(0)}% of ${u.floorFt2.toFixed(0)} ft² | ${zs.length} (main ${main.toFixed(0)} ft²) | ${u.levelsReached}/${u.levelsTotal} | ${(100 * u.reachableVoidFt3 / Math.max(1, u.voidFt3)).toFixed(0)}% | ${u.tightFt2.toFixed(0)} ft² |`);
  {
    const by: Record<string, string> = {};
    for (const c of printChecks(t)) {
      if (!checkKeys.includes(c.key + "|" + c.label)) checkKeys.push(c.key + "|" + c.label);
      by[c.key + "|" + c.label] = c.status === "ok" ? "ok" : `${c.status}: ${c.detail}`.slice(0, 70);
    }
    checkRows.push({ tag, by });
  }
  if (!keys.length) {
    keys.push(...e.results.map((r) => r.criterion.name));
    units.push(...e.results.map((r) => r.measure.unit || ""));
  }
  rows2.push(`| ${tag} | ` + e.results.map((r) => `${fmt(r.measure.value)}${r.measure.status === "proxy" ? "ᵖ" : r.measure.status === "assumed" ? "ᵃ" : ""}`).join(" | ") + " |");
}
for (const r of checkRows) rows3.push(`| ${r.tag} | ` + checkKeys.map((k) => r.by[k] ?? "-").join(" | ") + " |");
const out = [
  "# Tile set evaluation table (generated by `npx tsx scripts/tiles/table.ts`: do not edit)",
  "",
  `Read by the app's own code from \`lib/tiles/fixtures\` with the shared walking rules (6.5 ft headroom, 2.5 ft clear width, 0.5 ft step, 12 ft² minimum space).`,
  "",
  "## Floor, circulation, usability",
  "| tile | size ft | floor reached on foot from a ground opening | real floors (zones) | levels reached | void reached | too tight to use |",
  "|---|---|---|---|---|---|---|",
  ...rows1,
  "",
  "## The twelve descriptors (value; ᵖ proxy, ᵃ assumed; n/a = not assessable for this tile)",
  `| tile | ${keys.map((k, i) => (units[i] ? `${k} (${units[i]})` : k)).join(" | ")} |`,
  `|---|${keys.map(() => "---").join("|")}|`,
  ...rows2,
  "",
  "## Print and support checks (diagnostics only: they do not decide a tile)",
  `| tile | ${checkKeys.map((k) => k.split("|")[1]).join(" | ")} |`,
  `|---|${checkKeys.map(() => "---").join("|")}|`,
  ...rows3,
  "",
];
writeFileSync(join(__dirname, "..", "..", "engine", "tiles", "v7", "EVALUATION.md"), out.join("\n"));
console.log(out.join("\n"));
