"""Write recipes/REPORT.md: for every tile its concept, size facts, measurements, interlock scores and tile id.
Run after build_tiles.py (uses C:/tmp/tiles/cache from compat_matrix.py)."""
import glob
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "headless"))
sys.path.insert(0, HERE)
import tile_defs  # noqa: E402
from tile_report import metrics, pair_scores, port_map, compat  # noqa: E402
from compat_matrix import load_all, short  # noqa: E402

order = {"g": 0, "o": 1, "l": 2}
tiles = load_all(False)
names = sorted(tiles, key=lambda n: (order[n[0]], n))
doc = {}
for k, fn in tile_defs.TILES.items():
    rec = fn()
    doc[rec["name"]] = (k, (fn.__doc__ or "").strip().replace("\n    ", " "), rec)

lines = ["# Tile set: measurements", "",
         "Generated by `report_all.py` (headless engine, Rhino's bundled Python). Cell 0.5 ft. Foam = pink, void = rooms. Every recipe carries its tile id in `expect.tile_id`. Void % here is the final tile (as `tile.json` and the app will report it); the engine log's `VOID:` line counts before the last cleanup and reads 1 to 2 points lower.", ""]
lines += ["| Tile | Void % | Foam pieces | Thin foam % | repeat-x | repeat-y | mirror-x | mirror-y | shift-x | shift-y | rot90 | partners >= 60 | Tile id |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
allv = {n: tiles[n] for n in names}
rows = []
for n in names:
    v = allv[n]
    m = metrics(v, 0.5)
    ps = pair_scores(v, 0.5)
    partners = 0
    for o in names:
        if o == n or allv[o].shape != v.shape:
            continue
        s, _ = compat(v, allv[o])
        if s is not None and s >= 60:
            partners += 1
    tid = doc[n][2]["expect"]["tile_id"] if "expect" in doc[n][2] else ""
    p = json.load(open(os.path.join(HERE, "recipes", n + ".recipe.json")))
    tid = p.get("expect", {}).get("tile_id", "")
    sc = lambda k: "-" if ps.get(k) is None else "%d" % round(ps[k])  # noqa: E731
    lines.append("| %s `%s` | %.0f | %d | %.0f | %s | %s | %s | %s | %s | %s | %s | %d | `%s` |" % (
        doc[n][0], n, m["void_pct"], m["foam_pieces"], m["thin_foam_pct"], sc("repeat-x"), sc("repeat-y"), sc("mirror-x"), sc("mirror-y"),
        sc("shift-x"), sc("shift-y"), sc("rot90-x"), partners, tid))
    rows.append((n, m, ps))
lines += ["", "Scores are the app's joint rule (0 to 100, `-` = nothing opens onto that joint). `partners >= 60` counts the other tiles of the set whose best",
          "face-to-face joint with this tile, over all side faces and both directions (rotation and mirror allowed), scores 60 or more.", ""]
lines += ["## Tile by tile", ""]
for n, m, ps in rows:
    k, d, rec = doc[n]
    v = allv[n]
    lines += ["### %s `%s`" % (k, n), "", d, ""]
    lines.append("- Size: %s ft, weld `%s`. Void %.1f%% (%.0f ft3 of foam in %d piece(s)%s)." % (
        "20 x 20 x 20" if "container" not in rec else "x".join("%g" % a for a in rec["container"]["size"]), rec["cleanup"]["weld"] or "none",
        m["void_pct"], m["foam_ft3"], m["foam_pieces"], (", plus specks of %s ft3 on the faces" % ", ".join("%g" % a for a in m["foam_piece_ft3"][1:]) if m["foam_pieces"] > 1 else "")))
    lines.append("- Interlock: " + ", ".join("%s %s" % (a, "-" if s is None else round(s)) for a, s in ps.items()))
    lines += ["- Openings on the side faces (open share of each storey band; the bands are z 2-10 and z 12-20):", "", "```", port_map(v, 0.5), "```", ""]
open(os.path.join(HERE, "recipes", "REPORT.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("wrote REPORT.md")
